connectivity widget updated
SalihCanBinboga/recipe_finder pull request #19
Opened 2023-05-02 13:05 UTC by AcarFurkan

Connectivity widget updated and Necessary updates have been made.

2023-05-02 14:03 UTC, SalihCanBinboga requested changes

2023-05-02 14:03 UTC, SalihCanBinboga commented on lib/app/init/main_build.dart
> +        const ConnectivityWidget()
https://github.com/SalihCanBinboga/recipe_finder/pull/17#discussion_r1182510261
The answer to the question is here. By doing this, you are shrinking the content of the current screen with ConnectivityWidget, so we need to use Stack to prevent the content from being affected. 

Additionally, it is more appropriate to integrate this structure by wrapping the child inside the builder parameter with 'ConnectivityWidget' instead of creating an extra class like MainBuild.

2023-05-02 14:03 UTC, SalihCanBinboga commented on modules/core/lib/widget/connectivity_widget/connectivity_widget_state_mixin.dart
> +    _networkChange = NetworkManagerImpl.instance;
We need to handle `dispose` method inside the state. @AcarFurkan

2023-05-02 14:21 UTC, AcarFurkan commented on modules/core/lib/widget/connectivity_widget/connectivity_widget_state_mixin.dart
> +    _networkChange = NetworkManagerImpl.instance;
okay done 👍  thanks for review @SalihCanBinboga

2023-05-02 14:23 UTC, AcarFurkan commented on lib/app/init/main_build.dart
> +        const ConnectivityWidget()
okay, I got it now. I updated it in thought with different way.

2023-05-05 05:43 UTC, SalihCanBinboga approved these changes

2023-05-05 05:44 UTC, merged

2023-05-05 05:44 UTC, SalihCanBinboga commented
Thank you for your efforts, I have merged it into the main structure. @AcarFurkan